### ISSUE TITLE
Parse failing for background PID expression

### ISSUE THREAD

**Issue by sQVe** [mads-hartmann/bash-language-server#122]
There's an issue when I'm using `$!` to get the PID of the last background task. 

```sh
(sleep 1m && xset dpms force standby) &
dpms_standby=$!
```

In the above snippet it errors at `$` with the following text: `Failed to parse expression`.

**Comment by sQVe** [comment]
Also getting parse error for `>|`.

**Comment by skovhus** [comment]
Thanks for reporting this issue, and sorry for the late reply. 

In the meantime, it seems like the issue was fixed in the grammar we are using (https://github.com/tree-sitter/tree-sitter-bash). 

To upgrade run:
`npm i -g bash-language-server`

And if this doesn't solve the issue, can you to create an issue here (https://github.com/tree-sitter/tree-sitter-bash)?

**Comment by sQVe** [comment]
@skovhus Background PID expressions is now parsable. Overwrite redirections are not so I created the following issue: https://github.com/tree-sitter/tree-sitter-bash/issues/63
