### ISSUE TITLE
Failed to parse expression in eval string

### ISSUE THREAD

**Issue by NorthboundTrain** [mads-hartmann/bash-language-server#127]
I'm getting a "Failed to parse expression" error parsing the following line:

eval local rsync_host=\${IMAGE_SERVER:-\${v${ver}_IMAGE_SERVER}}

The red underlined part is the final closing brace (the last character on the line).

**Comment by skovhus** [comment]
Thanks for reporting this issue, and sorry for the late reply. 

In the meantime, it seems like the issue was fixed in the grammar we are using (https://github.com/tree-sitter/tree-sitter-bash). 

To upgrade run:
`npm i -g bash-language-server`

And if this doesn't solve the issue, can I get you to create an issue [here](https://github.com/tree-sitter/tree-sitter-bash)?
